# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and push docker latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alisamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: chmod +x ./gradlew
    - run: ./gradlew test
      
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    env: 
      LATEST_TAG: ai91/alisamqttbridge:latest
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
    defaults:
      run:
        working-directory: ./alisamqttbridge
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: chmod +x ./gradlew
    - run: ./gradlew bootBuildImage --imageName=ai91/alisamqttbridge:latest
    - name: run docker push
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: docker push $LATEST_TAG
